issuer: "${DEX_ISSUER}"

storage:
  type: "postgres"
  config:
    host: ${DEX_DB_HOST}
    port: ${DEX_DB_PORT}
    user: ${DEX_DB_USER}
    password: ${DEX_DB_PASSWORD}
    database: ${DEX_DB_NAME}
    ssl:
      mode: disable

web:
  http: 5556

oauth2:
  skipApprovalScreen: true
  responseTypes: ["token", "id_token", "code"]
  accessTokenLifetime: "10m"
  idTokenLifetime: "10m"

connectors: []

staticClients:
  - id: "${DEX_CLIENT_ID}"
    name: "${DEX_CLIENT_NAME}"
    secret: "${DEX_CLIENT_SECRET}"
    grantTypes: ["client_credentials"]
    redirectURIs: []

